name: 'Lint'

on:
  pull_request:
    types:
      - opened # PR opened
      - edited # PR title, body or base branch is edited

jobs:
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            ref
            perf
            test
            build
            ci
            chore
            revert
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically created to authenticate Github Actions